### ISSUE TITLE
Aimbot suggestion. - Viridian#1613

### ISSUE THREAD

**Issue by SeizaKokoro** [Lodington/Aerolt#10]
'I think the best way to 'fix' the aimbot right now is to limit the angle that the aimbot searches in again like how it worked in the older versions'
'Since right now it prioritizes all enemies in any angle which means it won't focus enemies where you're (roughly) aiming  at
I believe Bubbet said the angle was approx. 20 degrees in the direction the player is looking at before'

**Comment by Bubbet** [comment]
The aimbot in the dev release works miles better than the current one. Personally I don't even think it needs the filter.

**Comment by Lodington** [comment]
Added with Aerolt 4.0.0
