### ISSUE TITLE
Stage is empty when picked from Lunar Seer in Bazaar when teleported in menu.

### ISSUE THREAD

**Issue by moostoet** [Lodington/Aerolt#14]
Steps to reproduce:

1: Open the Teleporter menu.
2: Click on 'Hidden Realm: Bazaar Between Time'.
3: Pick a Lunar Seer stage in the Bazaar.
4: Exit the Bazaar through the regular portal and go to the next stage.
5: Observe that there are no interactables in the stage (Chests, Scrappers, Teleporter) apart from in-built ones (e.g. Fans on Rallypoint Delta).

This may also happen when using 'Skip Stage' in the Teleporter menu.

**Comment by Bubbet** [comment]
you actually fixed this?
