### ISSUE TITLE
Turning off "IRC"

### ISSUE THREAD

**Issue by LoganDark** [Lodington/Aerolt#18]
I load up the game just to find out this mod has connected me automatically to some chat server. WTF? How do I turn this off? Why is this turned on by default??

**Comment by Lodington** [comment]
Hey check out the Readme on the thunderstore. The Irc chat is a essential part of the mod

**Comment by LoganDark** [comment]
> Hey check out the Readme on the thunderstore

I did... it has a tiny "social" section, that says you can connect to the chat server, not that the mod will forcefully connect you by default

> The Irc chat is a essential part of the mod

How??

**Comment by LoganDark** [comment]
I will not use this mod if it forces me to be connected to chat, this is a disgusting anti-feature, and I think it's extra disgusting that there isn't a fair warning in the readme that this mod will connect to the chat server by default. Would put a warning in a rating if I could.

**Comment by Lodington** [comment]
Logan if you have read the Readme, you would have seen there is a irc chat sorry this has upset you. There is a privacy policy there if you'd like to check it out

**Comment by Lodington** [comment]
Logan I don't need your permission to connect you to a server, it's your job to read the Readme. This mod doesn't collect any personal data so I don't have to inform you. Informing you is a privilege.

**Comment by LoganDark** [comment]
> Logan if you have read the Readme, you would have seen there is a irc chat sorry this has upset you

I did read the README, and I have read it again (twice now) and have confirmed that there is nothing about the chat server being opened on startup. There is only

"Connect to a Chat server to invite and talk to people that are using aerolt"

which doesn't say it will happen automatically

> Logan I don't need your permission to connect you to a server, it's your job to read the Readme. 

Well you don't need my permission to infect my computer with malware but I would prefer if you didn't.

Like I said 3 times already, I *have* read the readme, and if you would look at the readme yourself, maybe you would see that it doesn't say anything about connecting to a chat server on startup.

> This mod doesn't collect any personal data so I don't have to inform you. Informing you is a privilege.

This is a pretty shitty thing to say and misses the entire point of the issue.

I don't care if you're collecting my data or not. I care that you're connecting me to a server without permission, and for the fourth time *there is no warning about it in the readme*, so there's no way I can avoid it just by *reading the readme*, which you have told me to do twice, and which I have done at least three times, and it does not say anything about connecting me to a chat server *automatically, by default, on startup, and cannot be turned off*.

**Comment by LoganDark** [comment]
By the way, this repository seems to be missing the code responsible for the "IRC" window and connection. It's also missing the "Social" section in the readme. Did you forget to publish it?

**Comment by Lodington** [comment]
The read me isn't updated for the github but if you go to the thunderstore there is a link to the repo for the server. And yes there is code for the social window it's the websocketclient.cs

**Comment by LoganDark** [comment]
> if you go to the thunderstore there is a link to the repo for the server

Yes, the thunderstore readme is the one that I've been reading

> And yes there is code for the social window it's the websocketclient.cs

Okay, thanks

**Comment by Bubbet** [comment]
Speaking from experience as a mod developer, having settings disabled by default means they will never get used. 90% of the people that use mods have no idea configs/settings in the options even exist.

**Comment by LoganDark** [comment]
> Speaking from experience as a mod developer, having settings disabled by default means they will never get used. 90% of the people that use mods have no idea configs/settings in the options even exist.

Most of the mods/clients/whatever that I've seen that have IRC support have it available as a 'cheat', i.e. as a toggle similar to what you already have for stuff like noclip or god mode. Is there a reason this doesn't work for you? You could add a button in the main menu to toggle it there too, just please don't connect me to anything by default.
