### ISSUE TITLE
Aimbot Issues - Viridian#1613

### ISSUE THREAD

**Issue by SeizaKokoro** [Lodington/Aerolt#3]
- Disable aimbot on things like mines, etc.? E.g. Engineer mines / Railgunner mine. For example, you wouldn't want to throw your mobility at enemies
- Disable aimbot aiming towards enemies not in line of sight? E.g. when there's enemies behind rocks but not directly visible to players. I don't know how achievable this is, but the old aimbot in the old Aerolt seemed to do this just fine (might just be placebo)

**Comment by Bubbet** [comment]
Disable aimbot is done via holding interact, and that is all you get. Implementing it per skill would be annoying.

**Comment by Bubbet** [comment]
The aiming towards code is much better now, and i've added a slider to control bias towards distance or angle.
