### ISSUE TITLE
menu doesn't open 

### ISSUE THREAD

**Issue by azerotj** [Lodington/Aerolt#32]
when I press F1 nothing happens.

**Comment by Lodington** [comment]
Are you using thunderstore Mod Manager?

**Comment by azerotj** [comment]
no, I installed the mod manually, in the plugins folder

**Comment by Lodington** [comment]
Aerolt requires several dependencies in order to function. I recommend you use r2modman as a mod manager.

**Comment by Lodington** [comment]
Send a logoutput.log

**Comment by azerotj** [comment]
Sorry, it turned out that I really didn’t have one dependency that I didn’t notice. Sorry to bother you, thanks for trying to help lol
